// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview AI agent that suggests suitable pesticides, manures, and fertilizers for recommended crops.
 *
 * - suggestProductRecommendations - A function that handles the product recommendation process.
 * - SuggestProductRecommendationsInput - The input type for the suggestProductRecommendations function.
 * - SuggestProductRecommendationsOutput - The return type for the suggestProductRecommendations function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const SuggestProductRecommendationsInputSchema = z.object({
  crop: z.string().describe('The recommended crop for the farmer.'),
  weather: z.string().describe('The current weather conditions.'),
  soilType: z.string().describe('The type of soil available.'),
  geographicRegion: z.string().describe('The geographic region of the farm.'),
  historicalYields: z.string().describe('Historical crop yields in the area.'),
  marketDemand: z.string().describe('Current market demand for the crop.'),
});
export type SuggestProductRecommendationsInput = z.infer<typeof SuggestProductRecommendationsInputSchema>;

const SuggestProductRecommendationsOutputSchema = z.object({
  pesticideRecommendation: z.string().describe('Recommended pesticide for the crop.'),
  manureRecommendation: z.string().describe('Recommended manure for the crop.'),
  fertilizerRecommendation: z.string().describe('Recommended fertilizer for the crop.'),
});
export type SuggestProductRecommendationsOutput = z.infer<typeof SuggestProductRecommendationsOutputSchema>;

export async function suggestProductRecommendations(input: SuggestProductRecommendationsInput): Promise<SuggestProductRecommendationsOutput> {
  return suggestProductRecommendationsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'suggestProductRecommendationsPrompt',
  input: {schema: SuggestProductRecommendationsInputSchema},
  output: {schema: SuggestProductRecommendationsOutputSchema},
  prompt: `You are an expert agricultural advisor. Based on the following information, recommend suitable pesticides, manures, and fertilizers for the recommended crop.

Crop: {{{crop}}}
Weather: {{{weather}}}
Soil Type: {{{soilType}}}
Geographic Region: {{{geographicRegion}}}
Historical Yields: {{{historicalYields}}}
Market Demand: {{{marketDemand}}}

Provide a clear and actionable recommendation for each product.
`,
});

const suggestProductRecommendationsFlow = ai.defineFlow(
  {
    name: 'suggestProductRecommendationsFlow',
    inputSchema: SuggestProductRecommendationsInputSchema,
    outputSchema: SuggestProductRecommendationsOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
