// This is an autogenerated file from Firebase Studio. Do not edit.
'use client';
import {useEffect} from 'react';
import {useRouter} from 'next/navigation';
import AppSidebar from '@/components/layout/sidebar';
import Header from '@/components/layout/header';
import {SidebarInset, SidebarProvider} from '@/components/ui/sidebar';
import ChatAssistant from '@/components/chat/chat-assistant';
import {useAuth} from '@/hooks/use-auth';
import {Loader2} from 'lucide-react';

export default function AppLayout({children}: {children: React.ReactNode}) {
  const {user, loading} = useAuth();
  const router = useRouter();

  useEffect(() => {
    if (!loading && !user) {
      router.push('/auth');
    }
  }, [user, loading, router]);

  if (loading || !user) {
    return (
      <div className="flex min-h-screen items-center justify-center">
        <Loader2 className="h-16 w-16 animate-spin text-primary" />
      </div>
    );
  }

  return (
    <SidebarProvider>
      <div className="min-h-screen">
        <AppSidebar />
        <SidebarInset>
          <Header />
          <div className="p-4 sm:p-6 lg:p-8">{children}</div>
        </SidebarInset>
        <ChatAssistant />
      </div>
    </SidebarProvider>
  );
}
