// This is an autogenerated file from Firebase Studio. Do not edit.
export default function AuthLayout({children}: {children: React.ReactNode}) {
  return (
    <div className="flex min-h-screen items-center justify-center bg-gray-100 dark:bg-gray-900">
      {children}
    </div>
  );
}
